---
- hosts: tensorflow
  sudo: yes
  tasks:
   - name: clone pyenv
     become: False
     git: repo=git://github.com/yyuu/pyenv.git dest=/home/vagrant/.pyenv accept_hostkey=yes

   - name: add bashrc
     lineinfile: dest=/home/vagrant/.bashrc line='{{ item.line }}'
     with_items:
      - line: 'export PYENV_ROOT="$HOME/.pyenv"'
      - line: 'export PYENV_ROOT="$PYENV_ROOT/bin:$PATH"'
      - line: 'eval "$(pyenv init -)"'
      - line: 'export PATH="$PYENV_ROOT/versions/anaconda3-5.1.0/bin/:$PATH"'

