---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars_files:
   - var.yaml
  tasks:
   - name: add a admin group
     group: name=admin state=present

   - name: add a new user
     user:
       name: "{{ item.name }}"
       uid: "{{ item.uid}}"
       password: "{{ item.password | password_hash('sha512') }}"
       group: admin
       groups: wheel
       generate_ssh_key: yes
       state: present
     with_items:
       - "{{ users }}"

   - name: mkdir publickey
     file:
       path: /home/vagrant/ansible/ansible_useradd/publickey/{{ item.name }}
       state: directory
       owner: "{{ item.name }}"
       group: admin
       mode: 0600
     with_items:
       - "{{ users }}"
