---
- hosts: all
  become: yes
  vars_files:
   - var.yaml
  tasks:
   - name: add a admin group
     group: name=admin state=present

   - name: add a new user
     user:
       name: "{{ item.name }}"
       uid: "{{ item.uid}}"
       password: "{{ item.password | password_hash('sha512') }}"
       group: admin
       groups: wheel
       state: present
     with_items:
       - "{{ users }}"

   - name: mkdir .ssh
     file:
       path: /home/{{ item.name }}/.ssh/
       state: directory
       owner: "{{ item.name }}"
       group: admin
       mode: 0700
     with_items:
       - "{{ users }}"

   - name: add authorized_key
     authorized_key:
       user: "{{ item.name }}"
       key: "{{ lookup('file', '/home/vagrant/ansible/ansible_useradd/publickey/{{ item.name }}/id_rsa.pub') }}"
     with_items:
       - "{{ users }}"
